# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# This is the starship configuration file.

# All configuration options can be found at https://starship.rs/config/

# Replace the 'â¯' symbol in the prompt with 'âœ'
[character]
success_symbol = "[âœ](bold green)"

# Set user name alias for "danesh.manoharan" to ğŸ¥·
[username]
show_always = true
[username.aliases]
"danesh.manoharan" = "ğŸ¥·"
